### ISSUE TITLE
Error relation "user_id_seq1" does not exist

### ISSUE THREAD

**Issue by qhartman** [haron/grafana-migrator#3]
Working on migrating a 5.4.3 installation and found my way here. Seeing the following when I run the migration, but only after it does a bunch of work. Not seeing where this `user_id_seq1` is coming from. Still working to run it down. Will post here if I find anything useful. If you happen to know the solution, I would love to hear it!

```
ERROR:  relation "user_id_seq1" does not exist
LINE 1: SELECT setval('user_id_seq1', (SELECT MAX(id)+1 FROM "user")...
```

**Comment by haron** [comment]
@qhartman thank you for your fix! It was definitely not a typo (I've checked my working database), but could be an issue anyway. Let's try your solution.

**Comment by svet-b** [comment]
Maybe this is a change between 5.4.0 and 5.4.3.

On 5.4.0 `user_id_seq1` does exist, but trying to set `user_id_seq` (as the current version of the code does) throws the equivalent of the above error.

**Comment by qhartman** [comment]
I bet it's one of those things that varies slightly at installation time
depending on the decisions the migrations make. Will probably have to add
some logic to the script to look for likely tables and guess a little.

**Comment by svet-b** [comment]
Right. Just noticed the comments at https://github.com/haron/grafana-migrator/pull/4 also, which indicate that maybe it's something more subtle. Maybe it's worth reopening this issue (or mentioning this in the docs), so that anyone else coming across this isn't as stumped.

**Comment by qhartman** [comment]
Yeah, now that we have more confidence in the root cause I think calling it
out in the docs is a great first step until some kind of automatic solution
can be put together
